### ISSUE TITLE
Incorrect footprints for ATMEGA168-20AU and FT232RL

### ISSUE THREAD

**Issue by PhirePhly** [KiCad/kicad-library#1304]
I'm working on laying out an Arduino board using a TQFP AVR, but it looks like neither component has the correct footprint assigned.

Steps to reproduce issue:
1. Create new project
2. Add FTDI library (Preferences -> Component Libraries -> Add -> /usr/share/kicad/library/ftdi.lib)
3. Place ATMEGA168-20AU (or any alias of it) & FT232RL
4. Annotate schematic
5. Tools -> Assign component footprints

KiCAD faults with the following messages instead of correctly assigning the expected footprints to these parts:
![screenshot from 2017-06-09 21-26-32](https://user-images.githubusercontent.com/131002/26999999-8743dc4e-4d5b-11e7-971c-440bdc684597.png)
![screenshot from 2017-06-09 21-26-51](https://user-images.githubusercontent.com/131002/26999998-8742ad56-4d5b-11e7-8f64-05a4138ca560.png)

I believe the correct footprints for these components are:
TQFP-32_7x7mm_Pitch0.8mm
SSOP-28_5.3x10.2mm_Pitch0.65mm

**Comment by poeschlr** [comment]
The ATMEGA168-20AU symbol is in the admel lib not in the ftdi lib. (At least in kicad 4.0.6 and in the current master branch.)

You are correct about the state of the symbol though. This symbol is in need of a major overhaul.
Or even worse: I think the complete atmel lib is in need of a major overhaul. (This is not the only symbol that has such a wrong footprint field.)

The footprint field is completely invalid. 
  - no footprint library given. Correct syntax: "pretty_lib_name:footprint_name"
  - the footprint filter is empty as well.
  - If it is correct that this device supports more than one footprint, the footprint field should be removed and the footprint filters set accordingly.

Other problems
- The datasheet link is dead
- The vcc and gnd pins should move to top/bottom.
- maybe the pin names should be shortened (The detailed function description can be removed. The port name is enough to identify the pin.)

A good model of how such a symbol could look like are the newly fixed symbols in the nxp armcpu library.
Example of such a pull request: https://github.com/KiCad/kicad-library/pull/1288

@PhirePhly would you be prepared to fix this symbol and submit it via a pull request?
(Otherwise it might take some time till somebody will fix it.)
