### ISSUE TITLE
Hirose connectors

### ISSUE THREAD

**Issue by G33KatWork** [KiCad/kicad-library#1406]
Hi,

Commit cf9ec51825a0a36b1d2495a3f25fd717bfe45081 added a bunch of Hirose connectors which I use all the time on my PCBs. And I just wondered where the 3d models that showed up by default in the past had gone.
I found that 13e8762dd361e8cb05795e032a171ca54e7a090c reverted a whole lot of stuff including the addition of the Hirose connectors in the earlier commit. Was this intended or by mistake? Because I'd really like to see these models to be readded so that I don't have to create my own library with all the models in them.

Thanks,
- Andy

**Comment by evanshultz** [comment]
Hi Andy,

I think you will want connectors at https://github.com/KiCad/Connectors_Hirose.pretty. This library was added to break out the footprints since we had so many connections. Sorry for any confusion.

You'll need to update your fp-lib-table file (https://github.com/KiCad/kicad-library/tree/master/template) to see the new libraries in KiCad. I believe I've seen an automated utility to do it some time in the past, but I can't find it now. If you go to Preferences > Footprint Libraries Manager in Pcbnew you will see the path at the top of the dialog.

Please reply if you run into more trouble!

**Comment by G33KatWork** [comment]
Thanks for your answer. I have the footprints, the 3d shapes are what is missing.
The footprints from https://github.com/KiCad/Connectors_Hirose.pretty even reference the old 3d shapes:

https://github.com/KiCad/Connectors_Hirose.pretty/blob/master/Hirose_DF13-02P-1.25DSA_02x1.25mm_Straight.kicad_mod#L45

**Comment by evanshultz** [comment]
Andy, my mistake. I didn't catch that you meant the 3D models.

@SchrodingersGat It looks like you merged. Can you take a look?

**Comment by SchrodingersGat** [comment]
@G33KatWork you have stumbled upon my shame.

I accidentally merged my personal libraries with the official KiCad libraries. I think perhaps you have been using the 3D models from those? The Hirose 3D models are not part of the official KiCad library dataset, due to licensing issues (all models must be submitted by the creator of the model).

If you are willing to develop these models for us? :) We have a powerful set of scripting tools for generating 3D models. Have a look at the examples in the [packages3d repo](https://github.com/kicad/packages3d)

**Comment by G33KatWork** [comment]
Are you sure we are talking about the same commit? There is a pull-request which deliberately added them: https://github.com/KiCad/kicad-library/pull/249, so at least the addition of the Hirose connectors don't look like an accident to me.

No offense, I just want to be sure that we are really talking about the same thing before I maybe try (no real experience in MCAD) to model them by myself.

**Comment by SchrodingersGat** [comment]
@G33KatWork you're right. It appears that the other commit erroneously removed these. Let me look into it.

**Comment by SchrodingersGat** [comment]
I have just submitted a PR to re-add these shapes - https://github.com/KiCad/kicad-library/pull/1407
