### ISSUE TITLE
KiCad release schedule

### ISSUE THREAD

**Issue by evanshultz** [KiCad/kicad-library#1508]
@SchrodingersGat (or anyone who knows)
Is there a public release schedule for KiCad? I understand 4.0.7 is coming, but when? I'm thinking about the library changes that have been discussed and other PRs that will/can be rolled into a stable release. Is there a soft or firm target release date?

**Comment by poeschlr** [comment]
Everything is communicated via the mailing list. (4.0.7 would have been released two weeks ago. But there where a few critical bugs that needed to be fixed.)
Current release announcement: https://lists.launchpad.net/kicad-developers/msg30236.html

Communication about the critical bugs. (In the later, wayne made it clear that he does not want a 4.0.8 release)
https://lists.launchpad.net/kicad-developers/msg30192.html
https://lists.launchpad.net/kicad-developers/msg30126.html

Original announcement of the pending 4.0.7 release. In this communication the decision not to ship new libs was made. (I read it too late. I think it is a bad idea because the footprint libs are automatically updated whereas 3d files are not. This leads to an inconsistent library.)
https://lists.launchpad.net/kicad-developers/msg29710.html
https://lists.launchpad.net/kicad-developers/msg30125.html
