### ISSUE TITLE
Resitor and capacitor symbols changed?

### ISSUE THREAD

**Issue by ondra6ak** [KiCad/kicad-library#196]
I've opend KiCad after a while of not using it and i've discovered, that symbols for resistor and capacitor are 1.27 mm shorter, therefore my schematic is borken...
Is there any explanation to that?

**Comment by keruseykaryu** [comment]
=> https://github.com/KiCad/kicad-library/pull/104

**Comment by ondra6ak** [comment]
OK
Why are there shorted symbols (compared to the rest of regular sized symbols) for resistor and unpolarized capacitor and at the same time R_small and C_small?

**Comment by CarlPoirier** [comment]
Can you be more clear? Which parts are you talking about?

**Comment by ondra6ak** [comment]
![screenshot_1432153317](https://cloud.githubusercontent.com/assets/5298002/7735640/c84970e0-ff3e-11e4-8eae-ce951557713d.jpg)

This screenshot shows it clearly, i think.
C11 is shorter then the rest of regular sized symbols.
It is the same with regular R symbol.

**Comment by samdolt** [comment]
Currently, we have two set of basic symbol, with two different length:

- Normal size ( R / CP / C / D )

- Small size ( R_Small / CP_Small / C_Small / D_Small )

This was a choice made in https://github.com/KiCad/kicad-library/pull/104 <https://github.com/KiCad/kicad-library/pull/104>

I think it’s useful to have this two size, because if you start a small project, bigger looks better. But in a project with
a lot of symbol in one sheet, smaller could be better.

**Comment by ondra6ak** [comment]
Oh, it's problem with KiCad loading symbols from cache.
I agree that the symbols are now better.
Thank you.

**Comment by CarlPoirier** [comment]
Glad to know you found the issue.

**Comment by Fat-Zer** [comment]
By the word, potentiometer symbol is left unchanged...

**Comment by CarlPoirier** [comment]
Indeed! I do think it could be made to match the normal size resistor.
