### ISSUE TITLE
Trouble with KLC Rule 6.9

### ISSUE THREAD

**Issue by evanshultz** [KiCad/kicad-library#820]
Here is my SOT-363 footprint based off of the existing SOT-353:
[SOT-363.kicad_mod.txt](https://github.com/KiCad/kicad-library/files/631649/SOT-363.kicad_mod.txt)

A simple change but the old one wasn't KLC compliant so I need to make a few updates. I can't figure out the violation of rule 6.6, though, which appeared after changing the text width to 0.12mm. Both text fields are clearly 1mm in height:
  (fp_text reference REF** (at 0 -1.8) (layer F.SilkS)
    (effects (font (size 1 1) (thickness 0.12)))
  )
  (fp_text value SOT-363 (at 0 2.2) (layer F.Fab)
    (effects (font (size 1 1) (thickness 0.12)))
  )

What am I missing?

(By the way, it seems odd to have SOT-353 in the library and not SOT-363, but that's what I found. Please correct me if SOT-363 exists and I just missed it. Thank you.)

**Comment by CarlPoirier** [comment]
Hi,

The script checks for 0.15mm thickness. It has not been specified in the KLC.

It's great to know you are adding the SOT-363, but make sure you base your work on the latest SOT-353. It has been recently updated [here](https://github.com/KiCad/TO_SOT_Packages_SMD.pretty/pull/15).

I will close this issue since it's not in the right repository. I suggest you open up your pull request and ask the questions there if you have any. We will also be able to witness your work and it will help us give you advice.
