### ISSUE TITLE
Hide Footprint field for All Components in All KiCAD libraries

### ISSUE THREAD

**Issue by kaitrek** [KiCad/kicad-library#893]
It does not make sense why anyone would want to show the footprint field in the schematic.
Now that KiCAD is implementing the new footprint identification system where library_name:footprint_name is VERY long, it will clutter up the schematic even more and force users to unnecessarily uncheck the Show checkbox for every component in their schematic.

Someone should run a batch operation to hide the footprint field for all components in kicad libraries.

**Comment by cpavlina** [comment]
Agreed 100%, the footprint names are ridiculously long now and nobody wants to see those all over their schematic.

**Comment by keruseykaryu** [comment]
I disagree. For example I want to see clearly footprint in Library Browser and when I select symbol to place.
The goal is not to hide it in the library because it is important information, but globally show/hide it by the user on the schematic. The code already exist - Eeeschema show a dialog and ask what to do with footprint fields after back annotate. The only thing is to connect this to some toolbar button or menu command to call this code at user demand.

**Comment by jkriege2** [comment]
I wold also like to have the fields hidden ... as said ... after back-annotate you can switch them on/off all at once! Also: We now usually add the name of the package to the part-description (at least where it makes sense, e.g. for ICs that come in different flavours), so this info is often available in the lib browser:
![2017-01-09 09_17_48-choose component 6716 items loaded](https://cloud.githubusercontent.com/assets/11967523/21760459/920d7a58-d64c-11e6-93ea-cbfb5bf453b1.png)

Maybe this could be even taken further: The symbol-selector already shows whether this is an Alias, shows the keywords, ... so why not also show the package there?


@keruseykaryu Still having such a button would be a nice addition ... are you planning on implementing that?


Best,
JAN

**Comment by keruseykaryu** [comment]
Sorry @jkriege2 my KiCad role has been self switched down from "involved user" to "basic user".

**Comment by cpavlina** [comment]
Perhaps the component selector should show all fields even if they are hidden, the same way the library editor does.

**Comment by SchrodingersGat** [comment]
I would even suggest displaying the footprint field explicitly:

![920d7a58-d64c-11e6-93ea-cbfb5bf453b1](https://cloud.githubusercontent.com/assets/10080325/21786811/002c9398-d71a-11e6-9c1f-83f316c1d104.png)

**Comment by evanshultz** [comment]
@kaitrek To directly answer you question: yes, they should. This is covered by rule 3.9 of the [KiCad Library Convention](https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention). Anywhere you don't see this happening, it's because the library is old and not yet been updated. This is a slow process but should eventually happen.

And I agree with the discussion... hide them on the schematic page by default, but show the info during component selection.

**Comment by SchrodingersGat** [comment]
PR here https://github.com/KiCad/kicad-library/pull/917/files

**Comment by SchrodingersGat** [comment]
This has been addressed :)
